#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=/dev/null
. "${ROOT}/options.sh"

cat <<EOF
KS_ARCH=${KS_ARCH}
KS_SUITE=${KS_SUITE}
KS_VARIANT=${KS_VARIANT}
KS_COMPONENTS=${KS_COMPONENTS}
KS_MIRROR=${KS_MIRROR}
KS_PACKAGES=${KS_PACKAGES}
KS_HOSTNAME=${KS_HOSTNAME}
KS_TIMEZONE=${KS_TIMEZONE}
KS_LOCALE=${KS_LOCALE}
KS_KB_KEYMAP=${KS_KB_KEYMAP}
KS_CREATE_USER=${KS_CREATE_USER}
KS_DEVICE_USER=${KS_DEVICE_USER}
KS_USER_SHELL=${KS_USER_SHELL}
KS_USER_GROUPS=${KS_USER_GROUPS}
KS_PASSWORD_CRYPT_METHOD=${KS_PASSWORD_CRYPT_METHOD}
KS_OUT_DIR=${KS_OUT_DIR}
EOF
