---
name: docker-engine
mmdebstrap:
  architectures:
    - arm64
  mirrors:
    - deb https://download.docker.com/linux/debian bookworm stable
  setup-hooks:
    - mkdir -p $1/usr/share/keyrings/
    - curl -fsSL https://download.docker.com/linux/debian/gpg -o $1/usr/share/keyrings/docker.asc
    - chmod a+r $1/usr/share/keyrings/docker.asc
    - cp -p $1/usr/share/keyrings/docker.asc $IGconf_sys_apt_keydir
  packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  customize-hooks:
    - mkdir -p $1/etc/apt/sources.list.d
    - |-
      cat <<- EOF > $1/etc/apt/sources.list.d/docker.list
      deb [arch=arm64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable
      EOF
    - sed -i '/download\.docker\.com/d' $1/etc/apt/sources.list
    - chroot $1 sh -c "groupadd -f -r docker"
