name: Build (bdebstrap + genimage)

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

# Cancel any in-progress run of this workflow when a new one starts for the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install all host dependencies (bdebstrap, genimage, qemu-user-static, etc.)
      - name: Install host dependencies
        run: |
          set -euo pipefail
          bash scripts/host-deps-apt.sh

      # Provide Debian archive signing keys for mmdebstrap
      - name: Provide Debian archive signing keys for mmdebstrap
        run: |
          set -eux
          sudo apt-get -o Acquire::Retries=3 -o DPkg::Lock::Timeout=600 update
          sudo apt-get -o Acquire::Retries=3 -o DPkg::Lock::Timeout=600 install -y debian-archive-keyring
          mkdir -p keydir
          cp /usr/share/keyrings/debian-archive-keyring.gpg keys/
          ls -l keydir

      # (Optional) Print the resolved config for debugging
      - name: Print config
        run: |
          set -euo pipefail
          if [ -f scripts/print-config.sh ]; then
            bash scripts/print-config.sh
          else
            echo "print-config.sh not present, skipping."
          fi

      # Build the rootfs and disk image (RPi-style) using bdebstrap + genimage
      - name: Build image
        run: |
          set -euo pipefail
          bash build.sh

      # Upload the image and log as artifacts
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspi-image-${{ github.sha }}
          path: |
            out/images/*.img
            out/BUILD_LOG.txt
            out/genimage.auto.cfg
          if-no-files-found: error
          retention-days: 14
```0
